# This file was generated by GoReleaser. DO NOT EDIT.
cask "trustdiff" do
  version "0.5.1"

  on_macos do
    on_arm do
      sha256 "41b85d1b838d770885e93cddce2391e2e648f1f1d76508b9ced15c823e1be26a"
      url "https://github.com/vahapogut/trustdiff/releases/download/v#{version}/trustdiff_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a1227bff9acce64a4af7a5c350745a9948cb2f5e28444622dca8c6bcd553ec9d"
      url "https://github.com/vahapogut/trustdiff/releases/download/v#{version}/trustdiff_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a6b286fb68e8393d0606d6c64f2fb2395a1bd48492c4aa7df25b97aa6aca724e"
      url "https://github.com/vahapogut/trustdiff/releases/download/v#{version}/trustdiff_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ec29f0201dbb185cde03f4c6671aa8b9e9566a2b05a29f1a6b3e8338407c856b"
      url "https://github.com/vahapogut/trustdiff/releases/download/v#{version}/trustdiff_#{version}_linux_amd64.tar.gz"
    end
  end

  name "trustdiff"
  desc "Finds trust regressions in a project's dependency tree before they land"
  homepage "https://github.com/vahapogut/trustdiff"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "trustdiff"

  # No zap stanza required
end
