# This file was generated by GoReleaser. DO NOT EDIT.
cask "trustdiff" do
  version "0.4.1"

  on_macos do
    on_arm do
      sha256 "be4212d60bc446dad33de75074bb790e8c98d647a0ec8d7c7f8b049189150ab9"
      url "https://github.com/vahapogut/trustdiff/releases/download/v#{version}/trustdiff_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8154a17d56e7c5eb91262e69556b2b83f0560ee1df25c739ccb7b0fb3cb4dd75"
      url "https://github.com/vahapogut/trustdiff/releases/download/v#{version}/trustdiff_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6d011ae5bf51e4e21a28e73815e076264dd833df80087290f49af94c93db28e8"
      url "https://github.com/vahapogut/trustdiff/releases/download/v#{version}/trustdiff_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9ff26ef6255d4fcbd0166af9bc9d9b9d74577e61a703b402e0ed5dc54ebf0f35"
      url "https://github.com/vahapogut/trustdiff/releases/download/v#{version}/trustdiff_#{version}_linux_amd64.tar.gz"
    end
  end

  name "trustdiff"
  desc "Finds trust regressions in a project's dependency tree before they land"
  homepage "https://github.com/vahapogut/trustdiff"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "trustdiff"

  # No zap stanza required
end
