# This file was generated by GoReleaser. DO NOT EDIT.
cask "trustdiff" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "3377b9f15b99528cd968a32088f7dbb485df7c30731d69a04f5c07c06aebe2f4"
      url "https://github.com/vahapogut/trustdiff/releases/download/v#{version}/trustdiff_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e944cbeea9925227dba2a66879a9e9e9d4a1881304a033b13cac711d80614375"
      url "https://github.com/vahapogut/trustdiff/releases/download/v#{version}/trustdiff_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4ba6ffec59fdee11fdb3175a03ad258252b8a3230e04ea283bff1f41dbdded75"
      url "https://github.com/vahapogut/trustdiff/releases/download/v#{version}/trustdiff_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "82dc406d9c569657b7903e2b59dd75f707e720f3fd2f66efe90971d575639d75"
      url "https://github.com/vahapogut/trustdiff/releases/download/v#{version}/trustdiff_#{version}_linux_amd64.tar.gz"
    end
  end

  name "trustdiff"
  desc "Finds trust regressions in a project's dependency tree before they land"
  homepage "https://github.com/vahapogut/trustdiff"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "trustdiff"

  # No zap stanza required
end
